apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: news-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: news-admin
subjects:
- kind: ServiceAccount
  name: news-api-user-janitor
