apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: news-writers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: news-writer
subjects:
- kind: User
  name: alice
